#!/usr/bin/env python3
"""Write manually curated SCOPE definitions and manuscript-derived worked cases.

These are interpretive summaries of the supplied manuscript, not independent
audits of the cited studies. Values not given in that source remain unknown.
"""
import copy
import json
import argparse
import hashlib
import re
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--source', type=Path, required=True, help='External LaTeX project containing manuscript.tex; not bundled with this site.')
parser.add_argument('--out', type=Path, required=True, help='Data directory previously generated by extract_references.py.')
args = parser.parse_args()
OUT = args.out
OUT.mkdir(parents=True, exist_ok=True)
manuscript_path = args.source / 'manuscript.tex'
manuscript_text = manuscript_path.read_text(encoding='utf-8-sig')
META = json.loads((OUT / 'reference-metadata.json').read_text(encoding='utf-8'))
assert hashlib.sha256(manuscript_path.read_bytes()).hexdigest() == META['source_sha256']['manuscript.tex'], 'Run extract_references.py for this source before building curated data.'
SOURCE = {'document': 'manuscript.tex', 'source_sha256': META['source_sha256']['manuscript.tex'], 'section': '3', 'section_title': 'The SCOPE Framework: Defining Governance Validity', 'label': 'sec:scope-framework'}


def save(name, value):
    (OUT / name).write_text(json.dumps(value, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')


statuses = [
    {'id': 'direct', 'short': 'D', 'definition': 'The target claim stays within the evaluated domain. This does not mean the evidence is strong.'},
    {'id': 'bridged', 'short': 'B', 'definition': 'A source–target comparison retains an identifiable toxicity endpoint, states an acceptable degradation, and supplies uncertainty analysis supporting that tolerance. The target must also meet the action’s absolute error or loss requirement.'},
    {'id': 'unsupported', 'short': 'U', 'definition': 'An identifiable inferential gap or contrary evidence prevents the stated extension.'},
    {'id': 'unreported', 'short': 'N', 'definition': 'The record cannot resolve the coordinate; C3 uses this status because its hypothetical target specifies no action.'},
]
coordinates = [
    {'id': 'S', 'name': 'Safety policy', 'question': 'Which harmful event, target, and context are governed?', 'definition': 'The policy maps an outcome, context, and target to a harm event. Category crosswalks preserve meaning; matching binary output formats does not establish policy equivalence.', 'record': ['categories and severity', 'targets and contexts', 'benign-sensitive cases', 'annotators and disagreement', 'source–target category crosswalk with exclusions and indeterminate cases'], 'failure_class': 'Policy substitution', 'unsupported_inference': 'One label set certifies every harm policy.'},
    {'id': 'C', 'name': 'Control channel and carrier', 'question': 'Through which routes can behavior change, and where is the evidence carried?', 'definition': 'A control channel permits behavior changes through prompts, history, images, retrieval, tools, decoding, embeddings, adapters, or fine-tuning. A carrier may be content, an interaction, a multimodal composition, a component, or the deployed system.', 'record': ['exposed routes', 'risk carriers', 'actor access', 'tested compositions', 'per-route tests'], 'failure_class': 'Channel omission', 'unsupported_inference': 'Prompt robustness certifies tools, images, or components.'},
    {'id': 'O', 'name': 'Observation and adjudication unit', 'question': 'What event is observed, with which information and judge?', 'definition': 'The governed unit, available information, and adjudication must match the claim: an artifact, request, response, refusal, trajectory, or executed component.', 'record': ['governed event', 'observation unit', 'information available at decision time', 'judge and adjudication procedure', 'indeterminate cases'], 'failure_class': 'Observation-unit substitution', 'unsupported_inference': 'Response toxicity equals intent, refusal quality, or system safety.'},
    {'id': 'P', 'name': 'Probability regime', 'question': 'Which population, system state, sampling procedure, and access budget define the event?', 'definition': 'Risk is conditional on the population, sampling, generation settings, version, and adversarial regime. Single outputs, repeated access, adaptive search, and changed compositions do not share an automatic probability interpretation.', 'record': ['population and input families', 'sampling and seeds', 'model and component versions', 'adversary and access budget', 'stopping rule', 'uncertainty at the actual sampling unit'], 'failure_class': 'Regime extrapolation', 'unsupported_inference': 'One seed or failed finite search establishes durable risk.'},
    {'id': 'E', 'name': 'Enforcement action', 'question': 'What decision follows, at which threshold and with which safeguards?', 'definition': 'Action links errors to costs, severity, reversibility, review capacity, and safeguards. Evidence sufficient for triage can be insufficient for automatic restriction or release.', 'record': ['action and threshold', 'loss and severity', 'abstention and review capacity', 'group burden', 'appeal and reversibility', 'monitoring and expiry'], 'failure_class': 'Action escalation', 'unsupported_inference': 'High AUC alone justifies automatic blocking or release.'},
]
save('scope-definitions.json', {'schema_version': '1.0', 'title': 'SCOPE: bounded evidence-to-action claims', 'source': SOURCE, 'purpose': 'Record what a claim’s evidence supports and what comparison is needed for a proposed extension.', 'coordinate_order': ['S', 'C', 'O', 'P', 'E'], 'coordinates': coordinates, 'support_statuses': statuses, 'method': ['State a target claim and the source result.', 'Identify the changed coordinates.', 'Inspect source–target comparisons and give a reason for each status.', 'Record judge validity, statistical precision, population coverage, and replication separately.', 'Narrow the claim or specify the transport test needed for an extension.'], 'limits': ['SCOPE is a proposed appraisal framework, not an empirically validated certification standard.', 'A coordinate match does not certify safety or establish policy legitimacy.', 'Contextual mechanisms alone establish neither direct nor bridged toxicity support.', 'Coordinate-wise bridges do not automatically compose; joint changes need joint evidence.', 'No worked case in this manuscript asserts a successful empirical bridge.'], 'evidence_roles': [{'id': 'direct_evidence', 'definition': 'Defines or measures the retained toxicity endpoint.'}, {'id': 'tested_bridge_evidence', 'definition': 'Compares source and target conditions for the retained endpoint using the declared tolerance and uncertainty criteria.'}, {'id': 'contextual_evidence', 'definition': 'Explains an architecture, attack, or governance mechanism without establishing toxicity performance.'}], 'role_note': 'Evidence roles apply to individual claims, not permanently to a publication. The role direct_evidence and coordinate status direct are related but are not interchangeable labels.'})

template = {
    'schema_version': '1.0', 'id': None, 'title': None, 'record_kind': 'evidence_card', 'record_status': 'unreviewed_template',
    'provenance': {'source_document': None, 'source_sha256': None, 'source_locations': [], 'reference_keys': [], 'curator': None, 'reviewer': None, 'reviewed_at': None, 'verification_level': None},
    'source_evidence': {'original_endpoint': None, 'object_and_configuration': None, 'source_result': None, 'valid_bounded_use': None, 'population_and_sampling_unit': None, 'denominators': [], 'judge_and_adjudication': None, 'limitations': [], 'evidence_role_for_this_claim': None},
    'target_claim': {'statement': None, 'is_hypothetical_extension': None, 'attribution_note': None, 'action': None},
    'coordinate_profile': {code: {'source_condition': None, 'target_condition': None, 'support_status': None, 'reason': None} for code in 'SCOPE'},
    'quality_notes': {'judge_validity': None, 'statistical_precision': None, 'population_coverage': None, 'independent_replication': None, 'other_limitations': []},
    'transport_test': {'design': None, 'matched_conditions': [], 'changed_coordinates': [], 'retained_endpoint': None, 'benign_sensitive_controls': None, 'adjudication': None, 'sampling_unit_and_uncertainty': None, 'acceptable_degradation': None, 'absolute_action_requirement': None, 'stopping_rule': None, 'result': None},
    'decision': {'supported_claim': None, 'unsupported_extension': None, 'recommended_next_evidence': [], 'expiry_or_retest_triggers': []},
    'use_note': 'A completed record is documentation, not proof of safety. Null means not filled in or not established by the cited material; it never means zero risk. Support status and evidence quality must be assessed separately.',
}
save('evidence-card-template.json', template)

case_data = [
    {
        'id': 'C1', 'title': 'Functional accuracy to conversation blocking', 'reference_keys': ['Rottger2021HateCheck'], 'source_line': 423,
        'original_endpoint': 'HateCheck’s constructed English functional hate-speech cases under the retained hate policy.',
        'source_result': 'The manuscript describes tests of 29 linguistic functions; its representative evidence table reports 3,728 cases.',
        'valid_bounded_use': 'Diagnosis of the represented linguistic functions.',
        'target_claim': 'The functional-suite results justify automatically blocking English conversations under the same hate policy.',
        'action': 'Automatically block English conversations.', 'profile': 'DUUUU',
        'reasons': ['The hypothetical claim explicitly holds the hate policy fixed.', 'Conversational history is outside the functional artifact tests.', 'Session adjudication is not established by artifact-level functional cases.', 'The constructed test distribution does not establish deployed conversation traffic performance.', 'Threshold-specific blocking errors and consequences are not validated.'],
        'source_conditions': ['Retained hate policy', 'Constructed English cases', 'Individual functional cases', 'Designed functional suite', 'Functional diagnosis'],
        'target_conditions': ['Same hate policy', 'Conversations with history', 'Sessions judged for blocking', 'English conversation traffic', 'Automatic blocking'],
        'limitations': ['The suite is not an estimate of deployment prevalence.', 'The deliberately extended claim is the survey’s worked example, not a claim attributed to the HateCheck authors.'],
        'transport_test': 'Pair artifact and session observations on an independently adjudicated conversation sample, retaining benign-sensitive controls and measuring threshold-specific errors.',
        'changed_coordinates': ['C', 'O', 'P', 'E'], 'supported_claim': 'The suite can diagnose the linguistic functions it represents.',
        'suggested_controls': 'Benign-sensitive conversations under the same policy.',
    },
    {
        'id': 'C2', 'title': 'Refusal detection to justified refusal', 'reference_keys': ['Han2024WildGuard'], 'source_line': 426,
        'original_endpoint': 'WildGuard’s separate prompt-harmfulness, response-harmfulness, and refusal-detection labels.',
        'source_result': 'The source study distinguishes these tasks; refusal-detection F1 measures identification of a refusal.',
        'valid_bounded_use': 'Identifying refusals and evaluating the separately defined task labels on the tested exchanges.',
        'target_claim': 'Refusal-detection F1 alone establishes justified blocking on the same exchanges.',
        'action': 'Justified blocking on those exchanges.', 'profile': 'DDUDU',
        'reasons': ['Policy is fixed in the hypothetical extension.', 'Input access and exchanges are fixed.', 'A refusal-occurrence label does not establish refusal appropriateness.', 'The evaluation population remains fixed.', 'A blocking rule requires consequences and policy-grounded appropriateness, not refusal detection alone.'],
        'source_conditions': ['Source policy', 'Access to the evaluated exchanges', 'Whether a refusal occurred', 'Tested exchanges and population', 'Refusal detection'],
        'target_conditions': ['Same policy', 'Same exchanges and access', 'Whether refusal is appropriate', 'Same population', 'Justified blocking'],
        'limitations': ['A refusal can still leak harmful information.', 'A safe response need not refuse.', 'This is an illustrative extended claim, not the WildGuard authors’ wording.'],
        'transport_test': 'Jointly assess the request’s policy status, response content, permitted safe alternatives, and intervention consequences. A new threshold on refusal occurrence is insufficient.',
        'changed_coordinates': ['O', 'E'], 'supported_claim': 'Refusal-detection performance supports the refusal-occurrence task under the tested conditions.',
        'suggested_controls': 'Harmful requests and benign-sensitive requests, including safe non-refusal answers.',
    },
    {
        'id': 'C3', 'title': 'One output to repeated-access exposure', 'reference_keys': [], 'source_line': 429,
        'original_endpoint': 'A hypothetical image-level failure rate under a fixed policy and interface.',
        'source_result': 'For fixed independent trials at a given prompt and configuration, repeated-access risk is analytically 1 − (1 − r)^n; the worked claim uses n = 100.',
        'valid_bounded_use': 'An image-level rate describes its stated single-output event. The analytic conversion applies only under the stated fixed-independent-trial assumptions.',
        'target_claim': 'The same image-level failure rate estimates harm within 100 attempts, with policy and interface fixed and no enforcement action specified.',
        'action': None, 'profile': 'DDUUN',
        'reasons': ['The hypothetical claim holds policy fixed.', 'The interface is fixed.', 'One-image failure and at least one failure within 100 attempts are different events.', 'Repeated access changes the probability regime; correlated or adaptive attempts require a distinct analysis.', 'No action is specified in this hypothetical claim. N does not mean demonstrated absence of evidence for a named action.'],
        'source_conditions': ['Fixed image harm policy', 'Fixed interface', 'One output', 'Single-output sampling regime', None],
        'target_conditions': ['Same policy', 'Same interface', 'At least one harmful output within 100 attempts', 'Repeated access with stated budget and stopping', None],
        'limitations': ['The case is hypothetical and is not an empirical audit of a named paper.', 'The equation does not cover dependent or adaptive attempts without additional analysis.', 'Averaging prompt-specific rates before the nonlinear conversion need not equal averaging their repeated-access risks.'],
        'transport_test': 'Measure prompt-level repeats with a declared stopping rule and quantify uncertainty at the prompt or session level; use the analytic conversion only for fixed independent trials.',
        'changed_coordinates': ['O', 'P'], 'supported_claim': 'The source rate concerns its specified image-level event.',
        'suggested_controls': 'Maintain a consistent policy and adjudication protocol across one-output and repeated-access measurements.',
    },
    {
        'id': 'C4', 'title': 'Static screening to component release', 'reference_keys': ['Xu2026ConceptQuickLook'], 'source_line': 432,
        'original_endpoint': 'Concept QuickLook’s original NSFW categories in static single-file embedding inspection; no toxicity crosswalk is established by this case.',
        'source_result': 'The manuscript describes SD 1.5/2.0 embedding inspection over 800 reviewed files (500 downloaded and 300 customized), with 15% marked NSFW. These numbers do not establish ecosystem prevalence.',
        'valid_bounded_use': 'Configuration-bound static concept inspection can prioritize further investigation; it does not validate automatic release.',
        'target_claim': 'Single-file embedding inspection justifies automatic release across arbitrary compatible compositions while retaining the original NSFW categories.',
        'action': 'Automatically release components across arbitrary compatible compositions.', 'profile': 'DUUUU',
        'reasons': ['D retains the source NSFW endpoint; it does not establish a mapping to targeted social harm.', 'Executed paths and arbitrary compatible compositions are not covered by a static single-file screen.', 'Static similarity does not observe generated outcomes after loading.', 'The distribution of compositions, bases, triggers, scales, and seeds is untested by static similarity.', 'Release costs and an operational release rule are not validated.'],
        'source_conditions': ['Original NSFW categories', 'Single-file static embedding inspection', 'Embedding similarity and metadata signals', 'Named embedding settings and reviewed sample', 'Inspection and screening'],
        'target_conditions': ['Same NSFW categories', 'Arbitrary compatible executions/compositions', 'Generated outcomes after loading', 'Composition distribution across bases, scales, triggers, and seeds', 'Automatic release'],
        'limitations': ['The reported Accuracy/FPR/FNR values are not jointly reconcilable under conventional binary definitions.', 'The metric inconsistency concerns evidence quality separately from coordinate support.', 'Several survey authors also authored Concept QuickLook.', 'The NSFW policy must not be silently relabeled targeted social harm or a general toxicity rate.'],
        'transport_test': 'Test both scanner-selected and scanner-cleared files on declared bases, scales, triggers, and seeds, with independent image adjudication and benign controls; reconcile the original metric definitions.',
        'changed_coordinates': ['C', 'O', 'P', 'E'], 'supported_claim': 'The static inspection feasibility result is bound to its original endpoint and tested configuration.',
        'suggested_controls': 'Benign controls and behavioral audits of both scanner-selected and scanner-cleared components.',
    },
]

status_map = {'D': 'direct', 'B': 'bridged', 'U': 'unsupported', 'N': 'unreported'}
cases, cards = [], []
for data in case_data:
    paragraph = re.search(r'\\paragraph\{' + re.escape(data['id']) + r':', manuscript_text)
    assert paragraph, f'Cannot locate {data["id"]}'
    data['source_line'] = manuscript_text[:paragraph.start()].count('\n') + 1
    profile = {code: {'status': status_map[short], 'reason': reason} for code, short, reason in zip('SCOPE', data['profile'], data['reasons'])}
    location = {**SOURCE, 'section': '3.3', 'section_title': 'Worked Claim Profiles and Transport Tests', 'label': 'sec:worked-profiles', 'source_line': data['source_line']}
    supplementary = {
        'C1': [{'section': '4.2', 'label': 'tab:content-scope-evidence', 'description': 'HateCheck function/case counts and bounded use.'}],
        'C2': [{'section': '5.2', 'description': 'Separate labels for harm and refusal.'}],
        'C3': [{'section': '5.1', 'label': 'eq:interactive-best-of-n-risk', 'description': 'Independent-trial conversion and its assumptions.'}],
        'C4': [{'section': '7.2', 'description': 'Concept QuickLook sample, metric limitations, and author overlap.'}],
    }[data['id']]
    cases.append({**{key: value for key, value in data.items() if key not in ['profile', 'reasons', 'source_conditions', 'target_conditions', 'source_line']}, 'kind': 'manuscript_worked_example', 'profile_short': '〈' + ', '.join(data['profile']) + '〉', 'coordinate_profile': profile, 'source': location, 'supplementary_manuscript_locations': supplementary, 'attribution_note': 'The survey deliberately extends a source result. This is not wording attributed to the original study and is not an independently performed study audit.', 'bridge_status': 'No successful empirical bridge claimed', 'empirical_results_added_by_companion': False})
    card = copy.deepcopy(template)
    card.update({'id': data['id'], 'title': data['title'], 'record_kind': 'manuscript_worked_example', 'record_status': 'source_derived_illustration_not_independent_audit'})
    card['provenance'].update({'source_document': 'manuscript.tex', 'source_sha256': SOURCE['source_sha256'], 'source_locations': [location] + supplementary, 'reference_keys': data['reference_keys'], 'verification_level': 'Checked against the supplied manuscript; primary studies not independently re-audited'})
    card['source_evidence'].update({'original_endpoint': data['original_endpoint'], 'source_result': data['source_result'], 'valid_bounded_use': data['valid_bounded_use'], 'limitations': data['limitations']})
    card['target_claim'].update({'statement': data['target_claim'], 'is_hypothetical_extension': True, 'attribution_note': 'Deliberately extended survey claim, not original authors’ wording.', 'action': data['action']})
    for idx, code in enumerate('SCOPE'):
        card['coordinate_profile'][code].update({'source_condition': data['source_conditions'][idx], 'target_condition': data['target_conditions'][idx], 'support_status': status_map[data['profile'][idx]], 'reason': data['reasons'][idx]})
    card['quality_notes']['other_limitations'] = data['limitations']
    card['transport_test'].update({'design': data['transport_test'], 'changed_coordinates': data['changed_coordinates'], 'retained_endpoint': data['original_endpoint'], 'benign_sensitive_controls': data['suggested_controls'], 'acceptable_degradation': 'Must be prespecified; no numerical tolerance is supplied by this worked case.', 'absolute_action_requirement': 'Must be established for the target action; no universal threshold is supplied.', 'result': 'Proposed test only; no empirical bridge result reported.'})
    card['decision'].update({'supported_claim': data['supported_claim'], 'unsupported_extension': data['target_claim'], 'recommended_next_evidence': [data['transport_test']]})
    if data['id'] == 'C3':
        card['transport_test']['absolute_action_requirement'] = 'Not specified because this hypothetical target claim names no enforcement action.'
    cards.append(card)

save('worked-cases.json', cases)
save('evidence-card-examples.json', cards)

# A deliberately modest JSON Schema that validates the reusable record shape.
coordinate_schema = {
    'type': 'object',
    'required': ['source_condition', 'target_condition', 'support_status', 'reason'],
    'properties': {
        'source_condition': {'type': ['string', 'null']},
        'target_condition': {'type': ['string', 'null']},
        'support_status': {'enum': ['direct', 'bridged', 'unsupported', 'unreported', None]},
        'reason': {'type': ['string', 'null']},
    },
}
schema = {
    '$schema': 'https://json-schema.org/draft/2020-12/schema',
    '$id': 'urn:scope-companion:evidence-card:1.0',
    'title': 'SCOPE evidence card',
    'type': 'object',
    'required': list(template),
    'properties': {
        'schema_version': {'const': '1.0'},
        'id': {'type': ['string', 'null']},
        'title': {'type': ['string', 'null']},
        'coordinate_profile': {
            'type': 'object',
            'required': list('SCOPE'),
            'additionalProperties': False,
            'properties': {code: coordinate_schema for code in 'SCOPE'},
        },
    },
    'description': 'Null preserves unfilled or unestablished information. Validation of this record’s structure does not establish evidence quality or safety.',
}
save('evidence-card.schema.json', schema)
print('Wrote SCOPE definitions, four worked examples, reusable template, example cards, and JSON Schema.')
